### Numpy - Numerical Python

In [ ]:
# Numpy is a library for python that helps us deal with arrays. It stands for Numerical Python. 
# Numpy base is C so it uses C datatypes behind the scenes though python datatypes are completely usable and no need to learn
# C datatypes.

# Arrays are a special datatype that we can use with large amounts of data. They have certain properties :

#1. The data is stored in 'contiguous' blocks of memory. Numpy will check if sufficient contiguous block of memory is
# available otherwise wont initialise the array.
#2. The elements in the array must be homogenous i.e. of the same datatype. Since they are homogenous, some metadata for the
# objects can now be stored in the arrays metadata
#3. They are faster than Python lists to process
#4. The elements along every axis must be of same length. 
#5. We can run arithmetic operations on array objects directly without running a for loop.
#6. We can run matrix operations on arrays.


In [ ]:
# a = 10 # I dont need to tell the program that 10 is an integer and I dont need to allocate memory

# # C

# a = int32 # Assign the datatype that can be stored in variable along with assigning a fixed memory size. 

In [ ]:
lst1 = [1,2,3,4]

print(lst1)


In [ ]:
import numpy as np

array1 = np.array(lst1)

print(array1)
print(type(array1))
print(array1.dtype)

In [ ]:
lstmix = [1,'a',2+3j,False,10.2, (10,20),{1:2,3:4}]

print(lstmix)

In [ ]:
arraymix = np.array(lstmix)

print(arraymix)
print(type(arraymix))
print(arraymix.dtype)

# For mixed datatypes - if array is not able to infer a suitable datatype it will convert it to object dtype. 

# Metadata of array - it will convert everything to object datatype. 

# Each object will have its metadata mentioning what dtype it actually is and it loses a little bit of its efficiency.

In [ ]:
lst1 = [[1,2,3,4],[10,20,30,40]]

print(lst1)

In [ ]:
array1 = np.array(lst1)

print(array1)

In [ ]:
lst1 = [[1,2,3,4],[10,20,30]]

print(lst1)

In [ ]:
array1 = np.array(lst1)

print(array1)

In [ ]:
lst1 = [list(range(1,11)),list(range(11,111,10))]

print(lst1)

In [ ]:
array1 = np.array(lst1)

print(array1)

In [ ]:
revised_outer = []

for size in range(len(lst1)):
    inner_lst = []
    for elem in range(len(lst1[size])):
        inner_lst.append(lst1[size][elem]*5)
    revised_outer.append(inner_lst)
    
print(revised_outer)
        

In [ ]:
array2 = array1*5

print(array2)

In [ ]:
array3 = np.random.randint(1,100,12).reshape(3,4)
array4 = np.random.randint(1,100,12).reshape(3,4)

print('array3 \n', array3)
print('array4 \n',array4)

In [ ]:
array5 = array3+array4

print(array5)

In [ ]:
lst1 = list(range(10000000))
array1 = np.arange(10000000)

print(len(lst1))
print(len(array1))

In [ ]:
%%time

newLst = []
for elem in lst1:
    newLst.append(lst1[elem]*2)
    

print(len(newLst))

In [ ]:
%%time

array2 = array1*2

print(len(array2))

In [ ]:
2300/28.2

In [ ]:
# Few methods and attributes which we will use for further understanding Numpy. 

# We WILL study the other functions and methods regularly used in your Data Science journey later. This is just a little
# bit of explanation of some common functions I will use. 

In [ ]:
# array

In [ ]:
array1 = np.array([1,2,3,4])

print(array1)

In [ ]:
array2 = np.array('abcde')

print(array2)
print(type(array2))
print(array2.dtype)

In [ ]:
array3 = np.array((1,2,3,4))

print(array3)

In [ ]:
array4 = np.array((1,2,3,4), dtype = float)

print(array4)
print(type(array4))
print(array4.dtype)

In [ ]:
# np.arange

array1 = np.arange(1,11,2)

print(array1)

In [ ]:
# shape

array2 = np.arange(1,301).reshape(3,2,5,10)

print(array2)

# shape 3 x 2 x 5 x 10

In [ ]:
# 10 elements along my inner axis  - X
# 5 elements of X along my middle axis - Y
# 2 elements of Y along my outer axis - Z
# 3 elements of Z along my OUTERMOST axis - A

In [ ]:
print(array2.shape)
print(array2.ndim)

In [ ]:
array1 = np.arange(10)

print(array1)
print(array1.shape)
print(array1.ndim)

In [ ]:
# random.randint

arrayrandom = np.random.randint(1,100,20).reshape(4,5)

print(arrayrandom)

In [ ]:
array1 = np.array([10,10.2,'1',100,1000], dtype = int )

print(array1)
print(array1.dtype)

### Array axes

In [ ]:
array1 = np.arange(5)

print(array1)
print(array1.shape)
print(array1.ndim)

In [ ]:
# Innermost axis has 5 elements. - I

# Axes are also zero index numbered

# 0 - Axis number
# 5,

In [ ]:
array1 = np.arange(20).reshape(4,5)

print(array1)
print(array1.shape)
print(array1.ndim)

In [ ]:
# Innermost axis has 5 elements. - I
# Middle axis has 4 elements of I - M

# Axes are also zero index numbered

# 0,1 - Axis number
# 4,5

In [ ]:
array1 = np.arange(60).reshape(3,4,5)

print(array1)
print(array1.shape)
print(array1.ndim)

In [ ]:
# Innermost axis has 5 elements. - I
# Middle axis has 4 elements of I - M
# First outer has 3 elements of M = FO

# Axes are also zero index numbered

# 0,1,2 - Axis number
# 3,4,5

In [ ]:
array1 = np.arange(120).reshape(2,3,4,5)

print(array1)
print(array1.shape)
print(array1.ndim)

In [ ]:
# Innermost axis has 5 elements. - I
# Middle axis has 4 elements of I - M
# First outer has 3 elements of M = FO
# Outermost has 2 elements of FO - OU

# Axes are also zero index numbered

# 0,1,2,4 - Axis number
# 2,3,4,5

In [ ]:
# Basic Indexing on Arrays

In [ ]:
array1 = np.random.randint(1,100,24).reshape(2,3,4)

print(array1)

In [ ]:
array1[0,1,2]

In [ ]:
array1[1,2,0]

In [ ]:
array1[1,2]

In [ ]:
array1 = np.random.randint(1,100,120).reshape(2,3,4,5)

print(array1)

In [ ]:
array1[:,1:,1:3]

In [ ]:
array1[:,1:,1:3,0]

In [ ]:
print(array1)

In [ ]:
array1[0,:,1:3]

In [ ]:
# 2,3,4,5

In [ ]:
print(array1)

In [ ]:
array1[0,1,3] = 123

In [ ]:
print(array1)

In [ ]:
import numpy as np

In [ ]:
array1 = np.random.randint(1,100,24).reshape(2,3,4)

print(array1)

In [ ]:
array1[0,1,1:3]

In [ ]:
array1[1]

In [ ]:
# Properties of arrays

#1. Elements are stored in contiguous blocks of memory.
#2. Elements of array must of homogenous data type. 
#3. No of elements along each axis must be same length. 
#4. Processing arrays is faster. 
#5. We can do arithmetic operations on arrays without running a loop.
#6. We can do matrix operations on arrays.


In [ ]:
# Slice assignment in lists: 

#1. Number of Assigned values do not have to match the number of values being assigned to. 
#2. Assigned values have to be put in an iterable. 

In [ ]:
import numpy as np

array1 = np.random.randint(1,100,24).reshape(2,3,4)

print(array1)

In [ ]:
# Numpy arrays slice assignment. 

In [ ]:
# A scalar value assigned to a slice - all the elements of the slice take on the scalar value

In [ ]:
array1[1,1,1:3] = 101

print(array1)

In [ ]:
# If we are assigning multiple values to a slice, then length of values being assigned must match length of values being 
# assigned to BECAUSE number of elements along each axis must be of same length is a fundamental property of arrays. 

In [ ]:
array1[1,1,1:3] = 101,102

print(array1)

In [ ]:
array1[1,1,1:3] = 101,102,103

print(array1)

### Boolean Indexing

In [ ]:
array1 = np.random.randint(1,100,10)

print(array1)

In [ ]:
array2 = array1*10

print(array2)

In [ ]:
array3 = array1 > 50

print(array3)

In [ ]:
array4 = np.array(list('abcdefghij'))

print(array4)

In [ ]:
array4[array3]

In [ ]:
names = np.array(['monisha', 'rashmika', 'bharath','taniya', 'pushpa'])
print(names)

In [ ]:
namesbool = names == 'bharath'

print(namesbool)

In [ ]:
marks = np.random.randint(80,100,5)

print(marks)

In [ ]:
marks[names == 'bharath']

In [ ]:
marks[(names == 'bharath') | (names == 'monisha')]



In [ ]:
marks[(names == 'bharath') or (names == 'monisha')]


In [ ]:
arraynames1 = names=='bharath'

print(arraynames1)

In [ ]:
arraynames2 = names == 'monisha'

print(arraynames2)

In [ ]:
arraynames3 = arraynames1 | arraynames2

print(arraynames3)

In [ ]:
marks2 = np.random.randint(80,101,25).reshape(5,5)

print(marks2)

In [ ]:
       sub1   sub2  sub3  sub4 sub5
stud1
stud2
stud3
stud4
stud5

In [ ]:
print(names)

In [ ]:
marks2[(names=='rashmika')|(names=='taniya')]

In [ ]:
subjects =  np.array(['Physics','Computer Science', 'English', 'Algebra', 'History'])

print(subjects)

In [ ]:
sub1 = (subjects=='Computer Science')
sub2 = (subjects == 'History')

print(sub1)
print(sub2)

In [ ]:
sub3 = sub1 | sub2

print(sub3)

In [ ]:
marks2[:,(subjects=='Computer Science')|(subjects == 'History')]

In [ ]:
print(marks2)

In [ ]:
array1 = np.random.randint(1,100,120).reshape(2,3,4,5)

print(array1)

In [ ]:
array1[:,:,0]

In [ ]:
#[axes0 (indexing/slicing),axes1(indexing/slicing),axes2 (indexing/slicing)...]

print(marks2)
print(names)
print(subjects)

In [ ]:
marks2[(names=='pushpa'), (subjects=='Computer Science') | (subjects=='Physics' )| (subjects=='Algebra')]


In [ ]:
(marks2[(names=='pushpa')]>90)

In [ ]:
marks2[names=='pushpa', marks2[(names=='pushpa')]>90]

In [ ]:
(marks2[(names=='pushpa')]>90)

In [ ]:
marks2[names=='pushpa']

In [ ]:
marks2[(names=='pushpa')]>90

In [ ]:
marks2[(names=='pushpa')][marks2[names=='pushpa']>90]

In [ ]:
import numpy as np
marks2 = np.random.randint(80,101,25).reshape(5,5)
names = np.array(['monisha', 'rashmika', 'bharath', 'taniya', 'pushpa'])
subjects = np.array(['Physics', 'Computer Science', 'English', 'Algebra', 'History'])

print(marks2)
print(names)
print(subjects)

In [ ]:
marks2[(names=='pushpa') & (marks2[(names=='pushpa')]>90)]

In [ ]:
result = marks2[(names == 'pushpa') & (marks2[names == 'pushpa']) > 90]
print(result)

#### Aggregation methods

In [ ]:
# np.sum, np.prod, np.cumsum, np.cumprod, np.min, np.max, np.argmin, np.argmax, np.mean, np.var, np.std

In [ ]:
array1 = np.arange(1,25).reshape(2,3,4)

print(array1)

In [ ]:
np.sum(array1)

In [ ]:
np.sum(array1, axis=0)

In [ ]:
# When performing aggregation methods such as np.sum, prod, min, max, argmin, argmax, mean, std and var along a certain
# axis - that axis 'collapses' and output is less by one dimension (the collapsed dimension)

In [ ]:
print(array1)

In [ ]:
array1.sum(1)

In [ ]:
array1.sum(2)

In [ ]:
#np.prod

array1 = np.random.randint(1,4,24).reshape(2,3,4)

print(array1)

In [ ]:
np.prod(array1)

In [ ]:
array1.prod(1)

In [ ]:
# cumsum

array1 = np.random.randint(1,10,24).reshape(2,3,4)

print(array1)

In [ ]:
array2 = array1.cumsum()

print(array2)
print(array2.shape)
print(array2.ndim)

In [ ]:
print(array1)

In [ ]:
array3 = array1.cumsum(2)

print(array3)

In [ ]:
array4 = array1.cumsum(0)

print(array4)

In [ ]:
# cumprod

array1 = np.random.randint(1,4,24).reshape(2,3,4)

print(array1)

In [ ]:
array1.cumprod(1)



In [ ]:
array1 = np.arange(1,25).reshape(2,3,4)

print(array1)

In [ ]:
array1.flatten()

In [ ]:
# min, max, argmin, argmax

array1 = np.random.randint(1,101,24).reshape(2,3,4)

print(array1)

In [ ]:
print(array1.min())
print(array1.max())

In [ ]:
print(array1.argmin())
print(array1.argmax())

In [ ]:
print(array1)

In [ ]:
print(array1.min(1))
print(array1.argmin(1))

In [ ]:
print(array1.min(2))
print(array1.argmin(2))

In [ ]:
# max, argmax - same as min and argmin but for max value.

In [ ]:
# mean

In [ ]:
print(array1)

In [ ]:
print(np.mean(array1))

In [ ]:
print(np.mean(array1, axis = 0))

In [ ]:
# var, std

In [ ]:
array1 = np.random.randint(1,50,24).reshape(2,3,4)

print(array1)

In [ ]:
print('var', array1.var())
print('std', array1.std())

In [ ]:
print('var', array1.var(0))
print('std', array1.std(0))

In [ ]:
#np.any, np.all

import numpy as np

array1 = np.random.randint(0,2,3)

print(array1)
print(array1.any())
print(array1.all())

In [ ]:
array1 = np.array([0,0,0])

print(array1)
print(array1.any())
print(array1.all())

In [ ]:
print(np.any(array1))

In [ ]:
# Most of your numpy   (any, all) functions become available to the array object as methods of that array class object. 

# e.g. 
# Using the numpy modules any function(also method actually)
# np.any(arrayobject)

# Using the method on the array object. 
# arrayobject.any()

### Homogenous N-Dimensional arrays

In [ ]:
# Constructs arrays of given shape - filled with zeros

zeros = np.zeros((3,4), dtype = int)

print(zeros)
print(type(zeros))

In [ ]:
# Constructs arrays of given shape - filled with ones

ones = np.ones((3,4))

print(ones)
print(type(ones))

In [ ]:
# Constructs arrays of given shape - filled with specified object

full = np.full((3,4),'a')

print(full)
print(type(full))

In [12]:
import numpy as np
# Constructs arrays of given shape - filled with garbage values (considered empty)

empty = np.empty((3,4))

print(empty)
print(type(empty))

[[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
 [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
 [8.45596650e-307 9.34602321e-307 4.94065646e-322 1.29060531e-306]]
<class 'numpy.ndarray'>


### Matrix Arrays

In [3]:
# Creates an identity matrix. An identity matrix is square and filled with 1s along the diagonal and 0s elsewhere.

identity = np.identity(5, dtype = bool)

print(identity)
print(type(identity))

[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]
<class 'numpy.ndarray'>


In [8]:
# Creates a sort of identity matrix with 1s on the diagonal and 0s elsewhere - but is not restricted to being square and
# is which diagonal the 1s appear can also be adjusted. 

eye = np.eye(5,4, k=-1)

print(eye)
print(type(eye))

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
<class 'numpy.ndarray'>


In [13]:
# If we pass a 1D array to the diagonal function - it puts the elements of the 1D array along the diagonal and creates a
# square matrix with 0s not along the diagonal.
# If we pass a 2D array to the diagonal function - it extracts the elements of the diagonal and returns the 1D array of these
# elements. 

# k parameter is used to place or extract the diagonal elements. 

diagonal = np.random.randint(1,11,5)

print(diagonal)

diagfunct = np.diag(diagonal, k = 1)

print(diagfunct)

[5 1 3 2 2]
[[0 5 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 2 0]
 [0 0 0 0 0 2]
 [0 0 0 0 0 0]]


In [15]:
newarray = np.random.randint(1,21,25).reshape(5,5)

print(newarray)

[[ 3 11  8  1 18]
 [12  6 17  6 10]
 [ 7  7  3  7  9]
 [17  9 11  2  8]
 [11 19  5 13  4]]


In [17]:
nArrayDiag = np.diag(newarray, k = -2)

print(nArrayDiag)

[7 9 5]


In [20]:
# np.fromfunct

# Will take two mandatory arguments
#1. A function on which to apply the co-ordinate values. 
#2. Shape of the output array

# It creates an array of given shape and fills up the values by passing the co-ordinates of each prospective element to 
# the function and placing the output at that co-ordinate position.

array1 = np.fromfunction(lambda x,y,z : (x+y)*z, (3,4,5))

print(array1)

[[[ 0.  0.  0.  0.  0.]
  [ 0.  1.  2.  3.  4.]
  [ 0.  2.  4.  6.  8.]
  [ 0.  3.  6.  9. 12.]]

 [[ 0.  1.  2.  3.  4.]
  [ 0.  2.  4.  6.  8.]
  [ 0.  3.  6.  9. 12.]
  [ 0.  4.  8. 12. 16.]]

 [[ 0.  2.  4.  6.  8.]
  [ 0.  3.  6.  9. 12.]
  [ 0.  4.  8. 12. 16.]
  [ 0.  5. 10. 15. 20.]]]


In [ ]:
0,0    0,1     0,2   0,3
1,0    1,1     1,2   1,3
2,0    2,1     2,2   2,3

In [21]:
# Comparison operators

array1 = np.random.randint(1,101,24).reshape(2,3,4)
array2 = np.random.randint(1,101,24).reshape(2,3,4)

print(array1)
print(array2)

[[[53 75 89 52]
  [52 35 74 81]
  [10 45 78 40]]

 [[39 75 34 36]
  [46 84 21 44]
  [25 44 45 16]]]
[[[23  4 61  8]
  [ 6 32 31 62]
  [ 3 67 51 41]]

 [[95 46 29 24]
  [42 82 30 50]
  [82 35 56 72]]]


In [22]:
array3 = array1 + array2
array4 = array1/array2

print(array3)
print(array4)

[[[ 76  79 150  60]
  [ 58  67 105 143]
  [ 13 112 129  81]]

 [[134 121  63  60]
  [ 88 166  51  94]
  [107  79 101  88]]]
[[[ 2.30434783 18.75        1.45901639  6.5       ]
  [ 8.66666667  1.09375     2.38709677  1.30645161]
  [ 3.33333333  0.67164179  1.52941176  0.97560976]]

 [[ 0.41052632  1.63043478  1.17241379  1.5       ]
  [ 1.0952381   1.02439024  0.7         0.88      ]
  [ 0.30487805  1.25714286  0.80357143  0.22222222]]]


In [23]:
array5 = array1 > array2

print(array5)

[[[ True  True  True  True]
  [ True  True  True  True]
  [ True False  True False]]

 [[False  True  True  True]
  [ True  True False False]
  [False  True False False]]]


### Broadcasting

In [24]:
array1 = np.random.randint(1,10,24).reshape(2,3,4)
array2 = np.random.randint(1,10,24).reshape(2,3,4)

print(array1)
array3 = array1 + 5
print(array3)

[[[8 5 6 9]
  [7 1 9 1]
  [9 6 8 6]]

 [[2 5 9 3]
  [8 6 6 9]
  [9 1 5 8]]]
[[[13 10 11 14]
  [12  6 14  6]
  [14 11 13 11]]

 [[ 7 10 14  8]
  [13 11 11 14]
  [14  6 10 13]]]


In [25]:
print(array1)
print(array2)

[[[8 5 6 9]
  [7 1 9 1]
  [9 6 8 6]]

 [[2 5 9 3]
  [8 6 6 9]
  [9 1 5 8]]]
[[[6 1 4 4]
  [3 3 4 3]
  [2 9 4 5]]

 [[4 8 4 2]
  [3 8 1 3]
  [4 1 3 3]]]


In [26]:
array4 = array1 + array2

print(array4)

[[[14  6 10 13]
  [10  4 13  4]
  [11 15 12 11]]

 [[ 6 13 13  5]
  [11 14  7 12]
  [13  2  8 11]]]


In [27]:
array5 = np.random.randint(1,10,12).reshape(3,4)

print(array5)

[[8 3 9 1]
 [8 1 3 2]
 [6 2 9 4]]


In [28]:
print(array1)

[[[8 5 6 9]
  [7 1 9 1]
  [9 6 8 6]]

 [[2 5 9 3]
  [8 6 6 9]
  [9 1 5 8]]]


In [29]:
array6 = array1 + array5

print(array6)

[[[16  8 15 10]
  [15  2 12  3]
  [15  8 17 10]]

 [[10  8 18  4]
  [16  7  9 11]
  [15  3 14 12]]]


In [38]:
array1 = np.random.randint(1,10,24).reshape(2,3,4)

array2 = np.random.randint(1,10,4).reshape(4)

print('Array1 \n'+'-'*125 + '\n'*2, array1)
print('Array2 \n'+'-'*125 + '\n'*2, array2)
print('Array1+2 \n'+'-'*125 + '\n'*2, array1+array2)

Array1 
-----------------------------------------------------------------------------------------------------------------------------

 [[[2 9 5 2]
  [8 1 8 5]
  [2 3 9 5]]

 [[1 4 6 1]
  [2 1 8 7]
  [5 1 5 8]]]
Array2 
-----------------------------------------------------------------------------------------------------------------------------

 [5 1 8 5]
Array1+2 
-----------------------------------------------------------------------------------------------------------------------------

 [[[ 7 10 13  7]
  [13  2 16 10]
  [ 7  4 17 10]]

 [[ 6  5 14  6]
  [ 7  2 16 12]
  [10  2 13 13]]]


In [45]:
# arange function
# Almost exactly like range function in python - but python range only accepts integers as start, stop and step values while
# arange function allows float values also besides integers as start, stop and step. 

# arange also allows the datetime datatype to get a range of dates - However, this we shall see when we do numpy datetme.

array1 = np.arange(1.5,7.2,0.1)
#lst1 = list(range(1,10,0.1))
print(array1)
#print(lst1)

[1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2
 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.
 5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8
 6.9 7.  7.1]


In [ ]:
#linspace

In [52]:
array1 = np.arange(1,25,0.5)

print(array1)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5
 22.  22.5 23.  23.5 24.  24.5]


In [53]:
arrayLin = np.linspace(1,50)

print(arrayLin)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50.]


In [ ]:
#Linspace - takes two values - start and stop and qives you 50 (by default - can be changed) EQUIDISTANT Points between those
# two values. 

In [ ]:
# arange - when we already know the distance we want between each element of our range. 
# linspace - when we have a range and number of elements - but dont know or dont want to calculate the distance between them.

In [ ]:
# It takes 7 arguments.

#1. Start - Mandatory
#2. Stop - Mandatory
#3. Num - Optional - Number of samples required between the range/interval. By default set to 50
#4. endpoint - Optional - By default set to true and includes the endpoint(i.e. stop value) - if set to False, returns
# equidistant numbers not including the endpoint/stop value.
#5 retstep - Optional - Default is False. If set to true, returns the samples and the step value (distance between samples)
#6 dtype - Optional - By default datatype will be inferred. However, for int datatype, float will be considered even if 
# start and stop are int.
#7 axis - Optional - By default 0 axis. Only useful in case start and stop are array-like.



In [61]:
arrayLin = np.linspace(1,50,25, endpoint = False, retstep = True, dtype = str)

print(arrayLin)

(array(['1.0', '2.96', '4.92', '6.88', '8.84', '10.8', '12.76',
       '14.719999999999999', '16.68', '18.64', '20.6', '22.56', '24.52',
       '26.48', '28.439999999999998', '30.4', '32.36', '34.32', '36.28',
       '38.24', '40.2', '42.16', '44.12', '46.08', '48.04'], dtype='<U32'), 1.96)


In [60]:
# 1 50  25

# 50 - 1 = 49/25 = 1.96

In [65]:
arrayLin = np.linspace((1,5),(10,50),20, axis = 1)

print(arrayLin)

[[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
   3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
   6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
   9.52631579 10.        ]
 [ 5.          7.36842105  9.73684211 12.10526316 14.47368421 16.84210526
  19.21052632 21.57894737 23.94736842 26.31578947 28.68421053 31.05263158
  33.42105263 35.78947368 38.15789474 40.52631579 42.89473684 45.26315789
  47.63157895 50.        ]]


### Random module

In [78]:
array1 = np.random.randint(1,100,10)

print(array1)

[59 42 92 60 80 15 62 62 47 62]


In [ ]:
# Random numbers for training, testing etc. 

# 1,000,000 million random numbers
# 800,000 as training values
# 200,000 as testing values

# model - 87% accurate
# model - 79% accurate


In [2]:
# Random module
# randint
# uniform
# rand
# randn
# choice
# permutation


# Other methods
# append
# vstack
# hstack
# sort
# insert
# transpose


# Datetime module
# datetime64
# timedelta64
# is_busday
# busday_count
# busday_offset


In [26]:
# randint - Gives us a random integer value between specified range. 

# It takes 4 parameters

#1. Low (or high) - If only low value provided then takes 0 as start and first value as stop 
#                 - If two values provided then takes first value as start and second value as stop.
#2. High - Second value - stop value. See #1. 
#3. Sample size = Integer or tuple for shape. If integer provided, n number of samples in 1D Array. If shape provided, 
# then number of samples required for that shaped array. e.g. for 2,3,4 = 24 samples required. 
#4. dtype - native numpy dtype (int only). 

import numpy as np

array1 = np.random.randint(5,8,size = (2,3,4))

print(array1)

[[[5 7 7 5]
  [7 5 5 7]
  [7 7 6 5]]

 [[6 5 7 5]
  [7 5 5 6]
  [7 5 6 7]]]


In [42]:
# uniform - gives us a random float value between specified range

# It takes 4 parameters

#1. Low (or high) - If only low value provided then takes 0 as start and first value as stop 
#                 - If two values provided then takes first value as start and second value as stop.
#2. High - Second value - stop value. See #1. 
#3. Sample size = Integer or tuple for shape. If integer provided, n number of samples in 1D Array. If shape provided, 
# then number of samples required for that shaped array. e.g. for 2,3,4 = 24 samples required. 
#4. dtype - native numpy dtype (int only). 


array1 = np.random.uniform(5)

print(array1)

2.9404669860237815


In [39]:
array1 = np.random.uniform(5,8)

print(array1)

6.823049359615469


In [40]:
array1 = np.random.uniform(5,8,10)

print(array1)

[5.39993153 7.61496672 7.78301125 6.67373648 6.48581115 7.70827347
 5.89568919 6.30677896 7.591975   7.37184137]


In [41]:
array1 = np.random.uniform(5,8,(2,3,4))

print(array1)

[[[5.44657045 5.95919203 6.63134856 7.55341217]
  [6.40554599 6.97340157 6.26365585 5.55596841]
  [7.25399025 5.43679305 7.07687195 5.65879086]]

 [[6.66230513 7.05360963 7.13723509 7.23921956]
  [7.64688022 7.5634172  5.4455557  6.299505  ]
  [6.19160172 7.89628247 7.93608637 7.64731182]]]


In [50]:
#rand function - gives a random float value between 0 and 1 only. 

# Takes one optional parameter
# 1. Size (Optional) - If integer provided then n number of samples in 1D array. If multiple integers separated by commas provided then
# returns an array of that shape. 

array1 = np.random.rand()

print(array1)

0.543094003618957


In [51]:
array1 = np.random.rand(2,3,4)

print(array1)

[[[0.88185343 0.53000764 0.91561276 0.94807329]
  [0.8092108  0.90057557 0.30319571 0.66142325]
  [0.63784548 0.52706867 0.53146341 0.73783076]]

 [[0.44646076 0.34025375 0.21205035 0.25112684]
  [0.03424372 0.03575773 0.39096046 0.2752693 ]
  [0.46626158 0.95881378 0.46661471 0.93049876]]]


In [60]:
#randn - gives random numbers from a normal distribution. Probabilities of obtaining a certain number follow the normal
# distribution probabilities. 

# Roughly - 68% of the values will be between -1 to 1
# Roughly - 95% of the values will be between -2 to 2, -2 to -1 and 1 to 2 - 27%
# Roughly - 99.2%  of the values will be between -3 to 3, -3 to -2 and 2 to 3 - 4.2%
# Roughly - 99.7% of the values will be between -4 to 4

# Takes integers as optional parameters to define the shape. 

# If no shape provided will return a single float value.


In [55]:
array1 = np.random.randn()

print(array1)

0.07710525651736583


In [57]:
array1 = np.random.randn()

print(array1)

-0.8588236779460311


In [58]:
array1 = np.random.randn(10)

print(array1)

[-1.67212223 -1.43815831  0.96382062 -0.25047264  0.47022349  0.17701083
  1.0698899   0.0360226   2.75868596 -0.60701693]


In [59]:
array1 = np.random.randn(2,3,4)

print(array1)

[[[ 0.01332022 -1.46479155  0.77011807 -1.31243235]
  [-1.30743049 -0.54164557 -1.76475849  0.76422551]
  [-0.26057017 -0.46604893 -0.88904441 -0.29982815]]

 [[ 2.06035101 -0.77646927  0.41705063 -0.47989882]
  [-0.46972257 -0.43877784  0.07679384  0.96512016]
  [ 0.31322349  0.25423966  0.18777767  1.71744826]]]


In [72]:
# permutation - Gives one possible permutation of the given values.

# Takes one mandatory parameter - lets call it X

# 1. If X is an integer does 'np.arange(X)' and then permutates the given values. 
#    If X is an array then permutates the given array (1D or multiDimensional) along axis 0 only.

array1 = np.arange(1,11)

print(array1)

[ 1  2  3  4  5  6  7  8  9 10]


In [63]:
permArray1 = np.random.permutation(array1)


print(permArray1)

[ 3 10  7  2  9  8  6  4  1  5]


In [68]:
array1 = np.arange(24).reshape(4,3,2)

print(array1)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [69]:
arrayPerm1 = np.random.permutation(array1)

print(arrayPerm1)

[[[12 13]
  [14 15]
  [16 17]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[18 19]
  [20 21]
  [22 23]]]


In [71]:
arrayPerm1 = np.random.permutation(25)

print(arrayPerm1)

[16 18  4  0 13  9 12 24 22 10 19 21  5 14  3  1 15 17 23 11  8  6 20  2
  7]


In [107]:
# choice - Chooses a random element from given elements

# Takes the following parameters:

#1. Integer or 1D Array to chose from - Mandatory. If integer provided then choses from np.arange(int). If 1D array provided
# choses from the 1D array
#2. Size - Optional - If not provided, choses one sample. If integer provided then outputs a 1D array with specified number
# of elements. If tuple of shape provided outputs array of specified shape. 
#3. replace - Default is True i.e. will replace back the chose value in the original array and allow it to be chosen again. 
# If changed to false, then once chosen a value cannot be chosen a second time. 
# *Note - when replace = true, we can chose a size of elements bigger than original array. If replace = false, then obviously
# we need to give a size <= len of original array. 
#4. p - Optional - Probabilities of chosing any particular value from the given array. Probabilities must always - 
# - Be given for every element existing in the array to be chosen from i.e. len p parameter must equal len input array. 
# - Must add up to 1 even though we are permitted to give 0 as probability for any particular value(s).



array1 = np.random.randint(1,100,10)
print(array1)

[75 84 15 57 61 85 54 89 62  5]


In [106]:
arrayChoice = np.random.choice(array1)

print(arrayChoice)

2


In [83]:
namesArray = np.array(['Sachin', 'Bharath', 'Apurv','Rashmika', 'Pushpa'])

print(namesArray)

arrayNamesChoice = np.random.choice(namesArray)

print(arrayNamesChoice)

['Sachin' 'Bharath' 'Apurv' 'Rashmika' 'Pushpa']
Sachin


In [90]:
arrayNamesChoice = np.random.choice(namesArray,3)

print(arrayNamesChoice)

['Pushpa' 'Sachin' 'Pushpa']


In [91]:
arrayNamesChoice = np.random.choice(namesArray,10)

print(arrayNamesChoice)

['Apurv' 'Apurv' 'Pushpa' 'Rashmika' 'Apurv' 'Pushpa' 'Rashmika' 'Pushpa'
 'Apurv' 'Bharath']


In [99]:
arrayNamesChoice = np.random.choice(namesArray,3, replace = False)

print(arrayNamesChoice)

['Rashmika' 'Apurv' 'Bharath']


In [103]:
arrayNamesChoice = np.random.choice(namesArray,(2,3,4), p=[0.1,0.4,0.15,0.30,0.05])

print(arrayNamesChoice)

[[['Rashmika' 'Apurv' 'Bharath' 'Sachin']
  ['Rashmika' 'Sachin' 'Rashmika' 'Bharath']
  ['Bharath' 'Rashmika' 'Sachin' 'Bharath']]

 [['Apurv' 'Bharath' 'Rashmika' 'Bharath']
  ['Bharath' 'Rashmika' 'Pushpa' 'Pushpa']
  ['Bharath' 'Bharath' 'Bharath' 'Bharath']]]


In [113]:
# Unlike in lists where a slice is a new object completely, slice of an array is a view of original

array1 = np.random.randint(1,20,(2,3,4))

print(array1)

[[[ 1  1 12 17]
  [13  9  2  2]
  [19 11 14  4]]

 [[ 7  2 17  6]
  [ 3 18  6  3]
  [ 6 17  3 16]]]


In [109]:
array2 = array1[0,1:,1:3]

print(array2)

[[ 9  9]
 [11  8]]


In [110]:
array2[0,1] = 900

print(array2)
print(array1)

[[  9 900]
 [ 11   8]]
[[[  8  10  11   4]
  [ 10   9 900  12]
  [ 18  11   8  19]]

 [[ 18  19  18   5]
  [ 15  12   8  13]
  [  2   1  17   1]]]


In [111]:
array3 = array1[0,1:,1:3].copy()

print(array3)

[[  9 900]
 [ 11   8]]


In [112]:
array3[0,1] = 999

print(array3)
print(array1)

[[  9 999]
 [ 11   8]]
[[[  8  10  11   4]
  [ 10   9 900  12]
  [ 18  11   8  19]]

 [[ 18  19  18   5]
  [ 15  12   8  13]
  [  2   1  17   1]]]


In [114]:
print(id(array1))
print(id(array2))
print(id(array3))

2871493809328
2871493810576
2871493810480


In [116]:
# append function - takes two array-like objects and appends the elements of the second to the first. 

# Takes an optional parameter - axis

#1. Axis = If no axis specified, flattens a multi-dimensional array and appends the elements from 2nd array to first. 
# If Axis specified, the appends the elements of specified axis from 2nd array to elements of specified axis from 1st array. 

array1 = np.arange(10)
array2 = np.arange(11,20)

print(array1)
print(array2)

array3 = np.append(array1,array2)

print(array3)

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]


In [119]:
array1 = np.arange(24).reshape(2,3,4)
array2 = np.arange(1,241,10).reshape(2,3,4)

print('Array1 \n' + '-'*125 + '\n',array1)
print('Array2 \n' + '-'*125 + '\n',array2)

Array1 
-----------------------------------------------------------------------------------------------------------------------------
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Array2 
-----------------------------------------------------------------------------------------------------------------------------
 [[[  1  11  21  31]
  [ 41  51  61  71]
  [ 81  91 101 111]]

 [[121 131 141 151]
  [161 171 181 191]
  [201 211 221 231]]]


In [120]:
array3 = np.append(array1, array2)

print(array3)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23   1  11  21  31  41  51  61  71  81  91 101 111
 121 131 141 151 161 171 181 191 201 211 221 231]


In [121]:
array4 = np.append(array1, array2, axis = 0)

print(array4)

[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]]

 [[  1  11  21  31]
  [ 41  51  61  71]
  [ 81  91 101 111]]

 [[121 131 141 151]
  [161 171 181 191]
  [201 211 221 231]]]


In [122]:
array4 = np.append(array1, array2, axis = 1)

print(array4)

[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]
  [  1  11  21  31]
  [ 41  51  61  71]
  [ 81  91 101 111]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]
  [121 131 141 151]
  [161 171 181 191]
  [201 211 221 231]]]


In [124]:
array1 = np.arange(24).reshape(2,3,4)
array2 = np.arange(1,241,10).reshape(2,3,4)

print('Array1 \n' + '-'*125 + '\n',array1)
print('Array2 \n' + '-'*125 + '\n',array2)

Array1 
-----------------------------------------------------------------------------------------------------------------------------
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Array2 
-----------------------------------------------------------------------------------------------------------------------------
 [[[  1  11  21  31]
  [ 41  51  61  71]
  [ 81  91 101 111]]

 [[121 131 141 151]
  [161 171 181 191]
  [201 211 221 231]]]


In [123]:
array4 = np.append(array1, array2, axis = 2)

print(array4)

[[[  0   1   2   3   1  11  21  31]
  [  4   5   6   7  41  51  61  71]
  [  8   9  10  11  81  91 101 111]]

 [[ 12  13  14  15 121 131 141 151]
  [ 16  17  18  19 161 171 181 191]
  [ 20  21  22  23 201 211 221 231]]]


In [126]:
# vstack = np.append(array1,array2, axis = 0)

array5 = np.vstack((array1,array2))

print(array5)

[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]]

 [[  1  11  21  31]
  [ 41  51  61  71]
  [ 81  91 101 111]]

 [[121 131 141 151]
  [161 171 181 191]
  [201 211 221 231]]]


In [127]:
# hstack - np.append(array1,array2, axis = 1)

array6 = np.hstack((array1,array2))

print(array6)


[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10  11]
  [  1  11  21  31]
  [ 41  51  61  71]
  [ 81  91 101 111]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]
  [121 131 141 151]
  [161 171 181 191]
  [201 211 221 231]]]


In [128]:
# sort - sorts the arrays on specified axis. By default 0 axis.

array1 = np.random.choice(24, 24, replace = False)

print(array1)

[22 15 20  6 16  0 23 18 17  9 14 19  7 13 10 12 21 11  3  8  5  1  4  2]


In [130]:
array2 = np.sort(array1)

print(array2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [131]:
array1 = np.random.choice(24, 24, replace = False).reshape(2,3,4)
print(array1)

[[[ 1 10 12 23]
  [11  7 18  6]
  [ 8 21 19 22]]

 [[ 5 20  3 15]
  [ 9 16 14 13]
  [ 2  0  4 17]]]


In [132]:
array3 = np.sort(array1, axis = 0)

print(array3)

[[[ 1 10  3 15]
  [ 9  7 14  6]
  [ 2  0  4 17]]

 [[ 5 20 12 23]
  [11 16 18 13]
  [ 8 21 19 22]]]


In [133]:
array3 = np.sort(array1, axis = 1)

print(array3)

[[[ 1  7 12  6]
  [ 8 10 18 22]
  [11 21 19 23]]

 [[ 2  0  3 13]
  [ 5 16  4 15]
  [ 9 20 14 17]]]


In [134]:
array3 = np.sort(array1, axis = 2)

print(array3)

[[[ 1 10 12 23]
  [ 6  7 11 18]
  [ 8 19 21 22]]

 [[ 3  5 15 20]
  [ 9 13 14 16]
  [ 0  2  4 17]]]


In [139]:
# insert - inserts values provided in the array on specific index positions.

array1 = np.arange(1,101,10)

print(array1)



[ 1 11 21 31 41 51 61 71 81 91]


In [136]:
array2 = np.insert(array1,4,100)

print(array2)

[  0   1   2   3 100   4   5   6   7   8   9]


In [140]:
array3 = np.insert(array1,[4,6,8], [1001,1002,1003])

print(array3)

[   1   11   21   31 1001   41   51 1002   61   71 1003   81   91]


In [141]:
array3D = np.arange(24).reshape(2,3,4)

print(array3D)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [143]:
Ax0 = np.random.randint(25,50,12).reshape(3,4)

print(Ax0)


[[35 38 41 33]
 [28 42 45 26]
 [28 49 39 46]]


In [144]:
array3DAx0 = np.insert(array3D, 1, Ax0, axis = 0)

print(array3DAx0)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[35 38 41 33]
  [28 42 45 26]
  [28 49 39 46]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [145]:
Ax1 = np.random.randint(25,50,8).reshape(2,4)

print(Ax1)

[[46 49 42 43]
 [46 30 46 40]]


In [146]:
array3DAx1 = np.insert(array3D, 2,Ax1, axis = 1)

print(array3DAx1)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [46 49 42 43]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [46 30 46 40]
  [20 21 22 23]]]


In [147]:
Ax2 = np.random.randint(25,50,6).reshape(2,3)

print(Ax2)

[[30 38 25]
 [25 37 43]]


In [148]:
array3DAx2 = np.insert(array3D, 0, Ax2, axis = 2)

print(array3DAx2)

[[[30  0  1  2  3]
  [38  4  5  6  7]
  [25  8  9 10 11]]

 [[25 12 13 14 15]
  [37 16 17 18 19]
  [43 20 21 22 23]]]


In [ ]:
# 2,3,4

# Axis 0 = 3,4
# Axis 1 = 2,4
# Axis 2 = 2,3

In [149]:
# Transpose

In [150]:
array1 = np.arange(12).reshape(3,4)

print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [151]:
array2 = array1.transpose()

print(array2)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [152]:
array1 = np.arange(24).reshape(2,3,4)

print(array1)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [153]:
array3 = array1.transpose(1,0,2)

print(array3)

[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


In [154]:
array4 = array1.transpose(1,2,0)

print(array4)

[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [ ]:
### datetime64 module

In [168]:
arrayDate = np.datetime64('2023-09-27')

print(arrayDate)
print(type(arrayDate))
print(arrayDate.dtype)

2023-09-27
<class 'numpy.datetime64'>
datetime64[D]


In [156]:
print(arrayDate+5)

2023-10-02


In [162]:
# Standard format for input to a datetime64 function is: 

# YYYY-MM-DDThh:mm:ss.ms

# You can truncate the input and exclude inputting 'T' but otherwise format HAS to be as above specified. 


arrayTime = np.datetime64('2023-09-27 09:50:59.999')

print(arrayTime)
print(type(arrayTime))

2023-09-27T09:50:59.999
<class 'numpy.datetime64'>


In [167]:
arrayTime = np.datetime64('2023-09-27 09:50')
print(arrayTime)
print(type(arrayTime))
print(arrayTime.dtype)

2023-09-27T09:50
<class 'numpy.datetime64'>
datetime64[m]


In [170]:
arrayTime = np.datetime64('2023-09-27 09')
print(arrayTime)
print(type(arrayTime))

print(arrayTime.dtype)

2023-09-27T09
<class 'numpy.datetime64'>
datetime64[h]


In [171]:
arrayTimeNew = arrayTime+5

print(arrayTimeNew)

2023-09-27T14


In [ ]:
# Common abbreviations are givin below

# Abbreviation - Meaning
# Y            - Years
# M            - Months
# D            - Days
# W            - Weeks
# h            - Hours
# m            - Minutes
# s            - Seconds


In [174]:
#timedelta64


TimeD = np.timedelta64(5,'D')

print(TimeD)
print(type(TimeD))
print(TimeD.dtype)

5 days
<class 'numpy.timedelta64'>
timedelta64[D]


In [176]:
arrayTimeNew = arrayTime + np.timedelta64(5,'D')

print(arrayTimeNew)



2023-10-02T09


In [178]:
arrayTimeNew = arrayTime + np.timedelta64(5,'m')

print(arrayTimeNew)


2023-09-27T09:05


In [177]:
arrayTimeYear = arrayTime + np.timedelta64(2,'Y')

print(arrayTimeYear)

UFuncTypeError: Cannot cast ufunc 'add' input 1 from dtype('<m8[Y]') to dtype('<m8[h]') with casting rule 'same_kind'

In [179]:
arrayTimeYear = arrayTime + np.timedelta64(2,'M')

print(arrayTimeYear)

UFuncTypeError: Cannot cast ufunc 'add' input 1 from dtype('<m8[M]') to dtype('<m8[h]') with casting rule 'same_kind'

In [180]:
arrayMonth = np.datetime64('2023-09')

print(arrayMonth)

2023-09


In [184]:
arrayYear = arrayMonth + np.timedelta64(2,'Y')

print(arrayYear)

2025-09


In [185]:
arrayToday = np.datetime64('today')

print(arrayToday)

2023-09-27


In [3]:
#is_busday
import numpy as np
print(np.is_busday(np.datetime64('2023-09-30')))

False


In [ ]:
# weekmask defaults to [1,1,1,1,1,0,0] - list (Starts with Monday and ends with Sunday)
# Can also be written as '1111100' - string of 1s and 0s for True and False
# Or - 'Mon Tue Wed Thu Fri Sat Sun' - Three letter abbreviation string

In [5]:
bday = np.is_busday(np.datetime64('2023-09-30'),weekmask = [1,1,1,1,1,1,0])

print(bday)

True


In [7]:
bday = np.is_busday(np.datetime64('2023-09-30'),weekmask = 'Mon Tue Wed Thu Fri Sat')

print(bday)

True


In [10]:
september = np.arange(np.datetime64('2023-09-01'),np.datetime64('2023-10-01'),2)

print(september)

['2023-09-01' '2023-09-03' '2023-09-05' '2023-09-07' '2023-09-09'
 '2023-09-11' '2023-09-13' '2023-09-15' '2023-09-17' '2023-09-19'
 '2023-09-21' '2023-09-23' '2023-09-25' '2023-09-27' '2023-09-29']


In [13]:
# arange along with weekmask and then boolean index on Sept

septTue = np.is_busday(np.arange(np.datetime64('2023-09-01'),np.datetime64('2023-10-01')),weekmask = '0100000')

print(septTue)

[False False False False  True False False False False False False  True
 False False False False False False  True False False False False False
 False  True False False False False]


In [14]:
septTue2 = np.arange(np.datetime64('2023-09-01'), np.datetime64('2023-10-01'))[septTue]

print(septTue2)

['2023-09-05' '2023-09-12' '2023-09-19' '2023-09-26']


In [15]:
#busday_count

busCountSept = np.busday_count('2023-09-01', '2023-10-01')

print(busCountSept)

21


In [17]:
septTue = np.is_busday(np.arange(np.datetime64('2023-09-01'),np.datetime64('2023-10-01')),weekmask = '1111100')

print(septTue.sum())


21


In [18]:
holidays = ['2023-10-02','2023-10-23','2023-10-24','2023-12-25','2023-12-31','2024-01-01']

busCountSept = np.busday_count('2023-09-01', '2024-02-02')

print(busCountSept)

110


In [19]:
busCountSept = np.busday_count('2023-09-01', '2024-02-02',holidays = holidays)

print(busCountSept)

105


In [24]:
#busday_offset

bdayoffset = np.busday_offset('2023-09-25',-1)

print(bdayoffset)

2023-09-22
