### Numpy 

- Numpy is a Python library. We call it a python library because it supports python syntax.
- It stands for Numerical python
- Numpy is used to perform advance numerical computations on large dataset
- By using, numpy we can perform complex operations with less lines of code
- Numpy provides a very useful data-structure known as array

### How to import Numpy ?

In [1]:
import numpy as np 

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__

In [3]:
a = np.array([1,2,3,4,5])
print(a, type(a))

[1 2 3 4 5] <class 'numpy.ndarray'>


### Version

In [4]:
np.__version__

'1.24.3'

### How to install Numpy ?


In [5]:
pip install Numpy

Note: you may need to restart the kernel to use updated packages.


### How to update Numpy?

- conda update Numpy on anaconda prompt
- Start> anaconda prompt

### Array 

- An array is a collection of Homogenous(Same type) elements 

In [9]:
lst = [1,2,3,4,5,6]
print(lst, type(lst))

[1, 2, 3, 4, 5, 6] <class 'list'>


In [10]:
arr = np.array(lst)
print(arr, type(arr))

[1 2 3 4 5 6] <class 'numpy.ndarray'>


### List vs Array

- With the array we can easily perform some operations that we could not easily perform over the list
- Arrays are going to be way faster 

In [11]:
lst = [i for i in range(1, 11)]
print(lst)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [13]:
#Multiply every element of this list with a 5 while using list only 

lst1 = [i*5 for i in lst]
print(lst1)

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]


In [16]:
lst2 = []

for i in lst:
    lst2.append(i*5)
print(lst2)

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]


In [14]:
#Multiply every element of this list with a 5 while using array only

arr = np.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

### Array are faster than the list

In [29]:
import time 

In [33]:
st = time.time()

lst = [i*5 for i in range(100000)]

end = time.time()

tt = end - st
print(tt)

0.00600123405456543


In [35]:
st = time.time()

arr = np.arange(100000)
arr*5

end = time.time()

tt = end-st

print(tt)

0.0009996891021728516


### Why arrays are faster than a list

- On list, we have to use a loop to perform some operation
- Loop makes the process slow 
- Array use vectorisation operation by using array broadcasting and this process will very fast
- List is a collection of heterogenous elements 
- A list has to store a lot of information for each element seperately because each element behaves differently in a list
- This makes the process slower
- An array is a collection of homogenous elements, it does not store extra information of the elements seperately

In [ ]:
v = (ai+bj+ck)*5
v = (ai+bj+ck)*(5i+5j+5k) # dot product i.i = 1, j.j = 1, k.k = 1, i.j = 0, i.k = 0, j.k = 0
v = (5a+5b+5c)

In [ ]:
v = [a,b,c]*5
v = [a,b,c]*[5,5,5]
v = [5a,5b,5c]

### Array upcasting

- When we pass heterogenous elements in an array, then it will convert them into 1 datatype and this process is called upcasting

In [ ]:
# int<float<complex<string<object 

In [36]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [37]:
arr = np.array([1,2.0,3,4,5])
arr

array([1., 2., 3., 4., 5.])

In [40]:
arr = np.array([1,2,3+7j,4,5])
arr

array([1.+0.j, 2.+0.j, 3.+7.j, 4.+0.j, 5.+0.j])

In [41]:
arr = np.array([1,2,3+7j,'4',5])
arr

array(['1', '2', '(3+7j)', '4', '5'], dtype='<U64')

In [44]:
arr = np.array([10, '20+9j', 30, 40, 50 ])
arr

array(['10', '20+9j', '30', '40', '50'], dtype='<U11')

In [42]:
arr = np.array([1,2,3+7j,'4',5], dtype = object)
arr

array([1, 2, (3+7j), '4', 5], dtype=object)

In [43]:
arr.dtype

dtype('O')

### Create Different Kinds of array 

### np.arange()

- It creates an array of numbers 

    Syntax:
    
        np.arange(start, stop, step_size)
        stop value - excluded
        step_size = 1

In [47]:
# create an array that has numbers from 1 to 10 

arr = np.arange(1,11,1)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
lst = [i for i in range(11)]
arr = np.array(lst)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### np.linspace()

- It creates an array of equally spaced values within a range of values 

        Syntax:- 
            
               np.linspace(start, stop, number of values)
               
               By default, in linspace both the start and stop values are included 
               By default, linspace will return the answer in float

In [52]:
# create an array of 5 equally spaced values between 1 and 3

np.linspace(1,3,5)

array([1. , 1.5, 2. , 2.5, 3. ])

In [53]:
# create an array of 10 equally spaced values between 1 and 3

np.linspace(1,3,10)

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [55]:
# create an array of 50 equally spaced values between 1 and 3

np.linspace(1,3,50)

array([1.        , 1.04081633, 1.08163265, 1.12244898, 1.16326531,
       1.20408163, 1.24489796, 1.28571429, 1.32653061, 1.36734694,
       1.40816327, 1.44897959, 1.48979592, 1.53061224, 1.57142857,
       1.6122449 , 1.65306122, 1.69387755, 1.73469388, 1.7755102 ,
       1.81632653, 1.85714286, 1.89795918, 1.93877551, 1.97959184,
       2.02040816, 2.06122449, 2.10204082, 2.14285714, 2.18367347,
       2.2244898 , 2.26530612, 2.30612245, 2.34693878, 2.3877551 ,
       2.42857143, 2.46938776, 2.51020408, 2.55102041, 2.59183673,
       2.63265306, 2.67346939, 2.71428571, 2.75510204, 2.79591837,
       2.83673469, 2.87755102, 2.91836735, 2.95918367, 3.        ])

### np.zeros

- It will return an array of the given shape with all the elements of the array as zero

        Syntax:-
        
            np.zeros((rows, columns))
            
            By default, it will return the answer in float

In [56]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [58]:
np.zeros((4,3), dtype = 'int32')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### np.ones()

- It will return an array of the given shape where all the elements are going to be 1 

        Syntax:-
        
            np.ones((rows, columns))
            
            By default, it will return the answer in float

In [59]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
np.ones((3,3), dtype = 'int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### np.full()

- It returns an array of the given shape and a given values 

       Syntax:
               
               np.full((rows, columns), value)
               
               By default, it will return you the answer in integer/
               

In [61]:
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [62]:
np.ones((3,3), dtype = 'int32')*5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

### np.eye()

- It will retunr an identity matrix
- In an identity matrix, the diagonal elements are 1's and the non diagonal elements are 0's
- by deafault, the values will be in float

In [63]:
# create an identity matrix 4*4 

np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
# create an identity matrix 4*4 

np.eye(4,4, dtype = 'int32')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### np.zeros_like()

- It returns an array of 0's of the given shape of another array

In [66]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
arr1 = np.zeros_like(arr)
arr1

array([[0, 0, 0],
       [0, 0, 0]])

### np.ones_like()

- It returns an array of 1's of the given shape of another array

In [69]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
arr2 = np.ones_like(arr)
arr2

array([[1, 1, 1],
       [1, 1, 1]])

### np.full_like()

- It returns an array of the given shape of another array having a particular value 

In [72]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
arr3 = np.full_like(arr, 10)
arr3

array([[10, 10, 10],
       [10, 10, 10]])

### np.diagonal()

- It return the principal diagonal from an array
- By default for this function, the offset = 0

In [86]:
arr = np.random.randint(10,100,36)
arr

array([13, 43, 24, 61, 28, 71, 56, 72, 31, 67, 34, 59, 71, 92, 67, 47, 51,
       65, 32, 74, 45, 41, 79, 57, 98, 91, 18, 37, 15, 85, 94, 16, 94, 80,
       75, 38])

In [87]:
arr = arr.reshape(6,6)
arr

array([[13, 43, 24, 61, 28, 71],
       [56, 72, 31, 67, 34, 59],
       [71, 92, 67, 47, 51, 65],
       [32, 74, 45, 41, 79, 57],
       [98, 91, 18, 37, 15, 85],
       [94, 16, 94, 80, 75, 38]])

In [79]:
z = np.diagonal(arr)
z

array([82, 19, 60, 52, 13, 58])

In [80]:
z = np.diagonal(arr, offset = 1)
z

array([16, 43, 69, 59, 61])

In [82]:
z = np.diagonal(arr, offset = 2)
z

array([67, 51, 29, 37])

In [81]:
z = np.diagonal(arr, offset = -1)
z

array([61, 20, 66, 11, 88])

In [83]:
z = np.diagonal(arr, offset = -2)
z

array([85, 93, 77, 77])

### np.diag()

- It returns a diagonal array
- In a diagonal array, the diagonal elements are non-zero rest every element is zero

    Syntax:-
        
        np.diag([diagonal])

In [84]:
a = np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [85]:
a.T

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])