### np.diagonal()

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(10,100, 36)
arr

array([44, 24, 11, 89, 64, 57, 29, 40, 38, 60, 75, 89, 78, 77, 75, 77, 47,
       11, 56, 43, 14, 37, 13, 51, 72, 13, 79, 39, 54, 26, 36, 35, 45, 19,
       94, 47])

In [4]:
arr = arr.reshape(6,6)
arr

array([[44, 24, 11, 89, 64, 57],
       [29, 40, 38, 60, 75, 89],
       [78, 77, 75, 77, 47, 11],
       [56, 43, 14, 37, 13, 51],
       [72, 13, 79, 39, 54, 26],
       [36, 35, 45, 19, 94, 47]])

In [5]:
z = np.diagonal(arr)
z

array([44, 40, 75, 37, 54, 47])

In [6]:
z = np.diagonal(arr, offset = 1)
z

array([24, 38, 77, 13, 26])

In [8]:
z = np.diagonal(arr, offset = -1)
z

array([29, 77, 14, 39, 94])

### np.trace()

- It return the sum of the diagonal of an array

In [9]:
arr

array([[44, 24, 11, 89, 64, 57],
       [29, 40, 38, 60, 75, 89],
       [78, 77, 75, 77, 47, 11],
       [56, 43, 14, 37, 13, 51],
       [72, 13, 79, 39, 54, 26],
       [36, 35, 45, 19, 94, 47]])

In [10]:
a = np.trace(arr)
a

297

In [11]:
44+40+75+37+54+47

297

In [12]:
z = np.diagonal(arr, offset = 1)
z

array([24, 38, 77, 13, 26])

In [13]:
a = np.trace(arr, offset = 1)
a

178

In [14]:
24+38+77+13+26

178

In [15]:
z = np.diagonal(arr, offset = -1)
z

array([29, 77, 14, 39, 94])

In [16]:
a = np.trace(arr, offset = -1)
a

253

### Attributes 

- These are some characteristics or Properties of an object, which are storing some kind of an information in them 

### Shape

- This tells us about the shape of the array 


In [17]:
n = np.random.random(24) # random.random will generate number between 0 and 1 
n

array([0.23943509, 0.3461558 , 0.33554855, 0.29894131, 0.37908988,
       0.61874117, 0.79615376, 0.14736042, 0.34406253, 0.19756699,
       0.50637152, 0.01370444, 0.41252469, 0.08867339, 0.83179902,
       0.3958035 , 0.78245502, 0.59934433, 0.76051502, 0.24288357,
       0.32548867, 0.24802186, 0.60143313, 0.32699154])

In [18]:
n.shape

(24,)

### Reshape 

- It reshapes the array as per the shape we have passed 
- It return a new array of the given shape, it doesnot make the changes in the existing array

In [20]:
n

array([0.23943509, 0.3461558 , 0.33554855, 0.29894131, 0.37908988,
       0.61874117, 0.79615376, 0.14736042, 0.34406253, 0.19756699,
       0.50637152, 0.01370444, 0.41252469, 0.08867339, 0.83179902,
       0.3958035 , 0.78245502, 0.59934433, 0.76051502, 0.24288357,
       0.32548867, 0.24802186, 0.60143313, 0.32699154])

In [21]:
n.shape

(24,)

In [22]:
n.reshape(12,2)

array([[0.23943509, 0.3461558 ],
       [0.33554855, 0.29894131],
       [0.37908988, 0.61874117],
       [0.79615376, 0.14736042],
       [0.34406253, 0.19756699],
       [0.50637152, 0.01370444],
       [0.41252469, 0.08867339],
       [0.83179902, 0.3958035 ],
       [0.78245502, 0.59934433],
       [0.76051502, 0.24288357],
       [0.32548867, 0.24802186],
       [0.60143313, 0.32699154]])

In [23]:
n.reshape(3,8)

array([[0.23943509, 0.3461558 , 0.33554855, 0.29894131, 0.37908988,
        0.61874117, 0.79615376, 0.14736042],
       [0.34406253, 0.19756699, 0.50637152, 0.01370444, 0.41252469,
        0.08867339, 0.83179902, 0.3958035 ],
       [0.78245502, 0.59934433, 0.76051502, 0.24288357, 0.32548867,
        0.24802186, 0.60143313, 0.32699154]])

In [24]:
n.reshape(6,4)

array([[0.23943509, 0.3461558 , 0.33554855, 0.29894131],
       [0.37908988, 0.61874117, 0.79615376, 0.14736042],
       [0.34406253, 0.19756699, 0.50637152, 0.01370444],
       [0.41252469, 0.08867339, 0.83179902, 0.3958035 ],
       [0.78245502, 0.59934433, 0.76051502, 0.24288357],
       [0.32548867, 0.24802186, 0.60143313, 0.32699154]])

### dtype

 - This tells us about the datatype stored in the array 

In [25]:
n

array([0.23943509, 0.3461558 , 0.33554855, 0.29894131, 0.37908988,
       0.61874117, 0.79615376, 0.14736042, 0.34406253, 0.19756699,
       0.50637152, 0.01370444, 0.41252469, 0.08867339, 0.83179902,
       0.3958035 , 0.78245502, 0.59934433, 0.76051502, 0.24288357,
       0.32548867, 0.24802186, 0.60143313, 0.32699154])

In [26]:
n.dtype

dtype('float64')

### Dimensionality - ndim

- This tells us about the dimension of the array

In [27]:
n = np.random.randint(10,100,36).reshape(2,3,3,2)
n

array([[[[57, 89],
         [25, 75],
         [63, 49]],

        [[45, 40],
         [62, 32],
         [84, 56]],

        [[79, 95],
         [55, 66],
         [30, 77]]],


       [[[41, 57],
         [20, 21],
         [26, 94]],

        [[26, 17],
         [21, 49],
         [61, 12]],

        [[91, 55],
         [41, 94],
         [84, 60]]]])

In [28]:
n.ndim

4

In [29]:
n = np.random.randint(10,100,36).reshape(3,3,4)
n

array([[[29, 37, 22, 56],
        [91, 37, 42, 27],
        [72, 70, 15, 56]],

       [[53, 30, 89, 65],
        [60, 51, 32, 33],
        [76, 51, 97, 24]],

       [[67, 37, 63, 30],
        [79, 10, 58, 69],
        [29, 27, 51, 14]]])

In [30]:
n.ndim

3

### Create a 2D array, 3D array and 4D array 

In [ ]:
list - 1D
list of a list - 2D
2 2D - 3D
2 3D - 4D

In [32]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [33]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
a = np.array([[[1,2,3,4], [5,6,7,8]], 
              [[1,2,3,4], [5,6,7,8]]])
a

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [35]:
a = np.array([[[[1,2,3,4], [5,6,7,8]], 
              [[1,2,3,4], [5,6,7,8]]], 
             [[[1,2,3,4], [5,6,7,8]], 
              [[1,2,3,4], [5,6,7,8]]]])
a

array([[[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[1, 2, 3, 4],
         [5, 6, 7, 8]]],


       [[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[1, 2, 3, 4],
         [5, 6, 7, 8]]]])

In [36]:
n = np.array([1,2,3])
n

array([1, 2, 3])

In [37]:
n.shape

(3,)

In [38]:
n = np.array([[1,2,3], [4,5,6]])
n

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
n.shape

(2, 3)

In [40]:
n = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
n

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [41]:
n.shape

(2, 2, 3)

number of layers, list in each layer, elements in each list 

In [42]:
n = np.random.random(24) # random.random will generate number between 0 and 1 
n

array([0.31075185, 0.64363528, 0.8993454 , 0.94614042, 0.02883916,
       0.5649789 , 0.57232465, 0.32399132, 0.9485152 , 0.49430502,
       0.47822086, 0.88813808, 0.09715862, 0.53655697, 0.12411725,
       0.76890707, 0.56859326, 0.18246954, 0.44926349, 0.56192658,
       0.32200315, 0.97218112, 0.43029323, 0.53666993])

In [43]:
n.reshape(3,4,2)

array([[[0.31075185, 0.64363528],
        [0.8993454 , 0.94614042],
        [0.02883916, 0.5649789 ],
        [0.57232465, 0.32399132]],

       [[0.9485152 , 0.49430502],
        [0.47822086, 0.88813808],
        [0.09715862, 0.53655697],
        [0.12411725, 0.76890707]],

       [[0.56859326, 0.18246954],
        [0.44926349, 0.56192658],
        [0.32200315, 0.97218112],
        [0.43029323, 0.53666993]]])

### Indexing and Slicing in Array

#### Indexing and Slicing in 1-D array

- the indexing and the slicing of a 1-D array is similar to the indexing and the slicing of a list
- Array will support both Positive and negative indexing

#### Indexing 

- Fetching the elements out form a particukar position or index 

        Syntax:
            
                arr[index]

In [44]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr.shape

(9,)

In [46]:
arr.ndim

1

In [47]:
# Fetch te first ite from the array 

arr[0] # Positive indexing
arr[-len(arr)] # Negative indexing


1

In [49]:
# Fetch the last element from the array 

arr[8]
arr[-1]
arr[len(arr)-1]

9

### Slicing 

    Synatx:
            arr[starting_index:ending_index:step_size)
            
              ending_index excluded
              step_size = 1

In [50]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
# Fetch the first five elements

print(arr[0:5])
print(arr[:5])
print(arr[0:5:1])

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [52]:
# Reverse the array 

arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [53]:
# Fetch every second element in the reverse order

print(arr[::-2])

[9 7 5 3 1]


### Indexing and Slicing in 2-D array 

- How many list are there in an array and how many elements are there in each list
- How many list out of the total we want and how many elements from the total we want

In [87]:
np.random.seed(1) # it is fixing the random state 
arr = np.random.randint(1,100,12)
arr

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2, 77, 72])

In [88]:
arr1 = arr.reshape(3,4)
arr1

array([[38, 13, 73, 10],
       [76,  6, 80, 65],
       [17,  2, 77, 72]])

In [89]:
arr1.ndim

2

In [90]:
len(arr1)

3

In [91]:
# fetch the first row 

print(arr1[0]) # Positive Indexing
print(arr1[-3]) # Negative Indexinh
print(arr1[-len(arr1)])

[38 13 73 10]
[38 13 73 10]
[38 13 73 10]


In [92]:
# fetch the last row 
print(arr1[2])
print(arr1[-1])
print(arr1[len(arr1)-1])

[17  2 77 72]
[17  2 77 72]
[17  2 77 72]


In [93]:
arr1

array([[38, 13, 73, 10],
       [76,  6, 80, 65],
       [17,  2, 77, 72]])

In [94]:
arr1[0][0]

38

#### Slicing in 2-D

##### arr[row_slicing]

arr[row_starting_index:row_endinhg_indexing:step_size]

##### arr[column_slicing]

arr[column_Starting_index: column_ending_index: step_size]

##### arr[row_Slicing, Column_slicing]

arr[row_starting_index:row_endinhg_indexing:step_size, column_Starting_index: column_ending_index: step_size]


In [95]:
arr1[0,0]

38

In [96]:
arr1

array([[38, 13, 73, 10],
       [76,  6, 80, 65],
       [17,  2, 77, 72]])

In [97]:
print(arr1[::, 0:1])

[[38]
 [76]
 [17]]


In [98]:
arr1[::, 1:3]


array([[13, 73],
       [ 6, 80],
       [ 2, 77]])

In [101]:
arr1

array([[38, 13, 73, 10],
       [76,  6, 80, 65],
       [17,  2, 77, 72]])

In [102]:
arr1[1:3, 2:4]


array([[80, 65],
       [77, 72]])

In [106]:
arr1[1:,2:]


array([[80, 65],
       [77, 72]])

In [107]:
arr1[1:, :3]

array([[76,  6, 80],
       [17,  2, 77]])

In [109]:
arr1

array([[38, 13, 73, 10],
       [76,  6, 80, 65],
       [17,  2, 77, 72]])

In [112]:
#         [[10,73,13,38],
#        [65,80,6,76],
#        [72,77,2,17]]

arr1[::,::-1]


array([[10, 73, 13, 38],
       [65, 80,  6, 76],
       [72, 77,  2, 17]])

In [113]:
#         [[72,77,2,17],
#        [65,80,6,76],
#        [10,73,13,38]]

arr1[::-1,::-1]


array([[72, 77,  2, 17],
       [65, 80,  6, 76],
       [10, 73, 13, 38]])

In [114]:
arr = np.random.randint(1,100,9).reshape(3,3)
arr

array([[ 7, 26, 51],
       [21, 19, 85],
       [12, 29, 30]])

In [115]:
np.diagonal(arr)

array([ 7, 19, 30])

In [118]:
np.diagonal(arr)[::-1]


array([30, 19,  7])