In [1]:
import numpy as np

### Condition Statements on array

In [4]:
np.random.seed(45)
arr = np.random.randint(10,100,12).reshape(3,4)
arr

array([[85, 40, 13, 42],
       [71, 95, 45, 78],
       [25, 75, 24, 63]])

arr_name[condition]

Where condition ---> boolean value

        arr[condition] ----> values

In [5]:
arr>60

array([[ True, False, False, False],
       [ True,  True, False,  True],
       [False,  True, False,  True]])

In [13]:
arr[arr>60]

array([85, 71, 95, 78, 75, 63])

In [10]:
arr

array([[85, 40, 13, 42],
       [71, 95, 45, 78],
       [25, 75, 24, 63]])

In [19]:
# filter out the elements that are divisible by both 5 and 2

arr[(arr%5 == 0) & (arr%2 == 0)]

array([40])

In [20]:
import seaborn as sns

In [21]:
df = sns.load_dataset('titanic')

In [22]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [28]:
# fetch out only female data
df[df['sex'] == "female"]


survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
8           1       3  female  27.0      0      2  11.1333        S   Third   
9           1       2  female  14.0      1      0  30.0708        C  Second   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
880         1       2  female  25.0      0      1  26.0000        S  Second   
882         0       3  female  22.0      0      0  10.5167        S   Third   
885         0       3  female  39.0      0      5  29.1250        Q   Third   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   

       who  adult_male deck  embark_town alive  alone  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
8    woman       False  NaN  Southampton   yes  False  
9    child       False  NaN    Cherbourg   yes  False  
..     ...         ...  ...          ...   ...    ...  
880  woman       False  NaN  Southampton   yes  False  
882  woman       False  NaN  Southampton    no   True  
885  woman       False  NaN   Queenstown    no  False  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  

[314 rows x 15 columns]

In [29]:
df[(df['sex'] == 'female') & (df['pclass'] == 1)]

survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
1           1       1  female  38.0      1      0   71.2833        C  First   
3           1       1  female  35.0      1      0   53.1000        S  First   
11          1       1  female  58.0      0      0   26.5500        S  First   
31          1       1  female   NaN      1      0  146.5208        C  First   
52          1       1  female  49.0      1      0   76.7292        C  First   
..        ...     ...     ...   ...    ...    ...       ...      ...    ...   
856         1       1  female  45.0      1      1  164.8667        S  First   
862         1       1  female  48.0      0      0   25.9292        S  First   
871         1       1  female  47.0      1      1   52.5542        S  First   
879         1       1  female  56.0      0      1   83.1583        C  First   
887         1       1  female  19.0      0      0   30.0000        S  First   

       who  adult_male deck  embark_town alive  alone  
1    woman       False    C    Cherbourg   yes  False  
3    woman       False    C  Southampton   yes  False  
11   woman       False    C  Southampton   yes   True  
31   woman       False    B    Cherbourg   yes  False  
52   woman       False    D    Cherbourg   yes  False  
..     ...         ...  ...          ...   ...    ...  
856  woman       False  NaN  Southampton   yes  False  
862  woman       False    D  Southampton   yes   True  
871  woman       False    D  Southampton   yes  False  
879  woman       False    C    Cherbourg   yes  False  
887  woman       False    B  Southampton   yes   True  

[94 rows x 15 columns]

In [35]:
df[(df['sex'] == 'female') & (df['pclass'] ==1 )]

survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
1           1       1  female  38.0      1      0   71.2833        C  First   
3           1       1  female  35.0      1      0   53.1000        S  First   
11          1       1  female  58.0      0      0   26.5500        S  First   
31          1       1  female   NaN      1      0  146.5208        C  First   
52          1       1  female  49.0      1      0   76.7292        C  First   
..        ...     ...     ...   ...    ...    ...       ...      ...    ...   
856         1       1  female  45.0      1      1  164.8667        S  First   
862         1       1  female  48.0      0      0   25.9292        S  First   
871         1       1  female  47.0      1      1   52.5542        S  First   
879         1       1  female  56.0      0      1   83.1583        C  First   
887         1       1  female  19.0      0      0   30.0000        S  First   

       who  adult_male deck  embark_town alive  alone  
1    woman       False    C    Cherbourg   yes  False  
3    woman       False    C  Southampton   yes  False  
11   woman       False    C  Southampton   yes   True  
31   woman       False    B    Cherbourg   yes  False  
52   woman       False    D    Cherbourg   yes  False  
..     ...         ...  ...          ...   ...    ...  
856  woman       False  NaN  Southampton   yes  False  
862  woman       False    D  Southampton   yes   True  
871  woman       False    D  Southampton   yes  False  
879  woman       False    C    Cherbourg   yes  False  
887  woman       False    B  Southampton   yes   True  

[94 rows x 15 columns]

In [45]:
# fetch out the record where the sex should male, pclass is 1, survived 

df[(df['sex'] == 'male') & (df['pclass'] ==1) & (df['survived'] == 1)]

survived  pclass   sex    age  sibsp  parch      fare embarked  class  \
23          1       1  male  28.00      0      0   35.5000        S  First   
55          1       1  male    NaN      0      0   35.5000        S  First   
97          1       1  male  23.00      0      1   63.3583        C  First   
187         1       1  male  45.00      0      0   26.5500        S  First   
209         1       1  male  40.00      0      0   31.0000        C  First   
224         1       1  male  38.00      1      0   90.0000        S  First   
248         1       1  male  37.00      1      1   52.5542        S  First   
298         1       1  male    NaN      0      0   30.5000        S  First   
305         1       1  male   0.92      1      2  151.5500        S  First   
370         1       1  male  25.00      1      0   55.4417        C  First   
390         1       1  male  36.00      1      2  120.0000        S  First   
430         1       1  male  28.00      0      0   26.5500        S  First   
445         1       1  male   4.00      0      2   81.8583        S  First   
447         1       1  male  34.00      0      0   26.5500        S  First   
449         1       1  male  52.00      0      0   30.5000        S  First   
453         1       1  male  49.00      1      0   89.1042        C  First   
460         1       1  male  48.00      0      0   26.5500        S  First   
484         1       1  male  25.00      1      0   91.0792        C  First   
507         1       1  male    NaN      0      0   26.5500        S  First   
512         1       1  male  36.00      0      0   26.2875        S  First   
550         1       1  male  17.00      0      2  110.8833        C  First   
572         1       1  male  36.00      0      0   26.3875        S  First   
587         1       1  male  60.00      1      1   79.2000        C  First   
599         1       1  male  49.00      1      0   56.9292        C  First   
604         1       1  male  35.00      0      0   26.5500        C  First   
607         1       1  male  27.00      0      0   30.5000        S  First   
621         1       1  male  42.00      1      0   52.5542        S  First   
630         1       1  male  80.00      0      0   30.0000        S  First   
632         1       1  male  32.00      0      0   30.5000        C  First   
645         1       1  male  48.00      1      0   76.7292        C  First   
647         1       1  male  56.00      0      0   35.5000        C  First   
660         1       1  male  50.00      2      0  133.6500        S  First   
679         1       1  male  36.00      0      1  512.3292        C  First   
681         1       1  male  27.00      0      0   76.7292        C  First   
690         1       1  male  31.00      1      0   57.0000        S  First   
701         1       1  male  35.00      0      0   26.2875        S  First   
707         1       1  male  42.00      0      0   26.2875        S  First   
712         1       1  male  48.00      1      0   52.0000        S  First   
724         1       1  male  27.00      1      0   53.1000        S  First   
737         1       1  male  35.00      0      0  512.3292        C  First   
740         1       1  male    NaN      0      0   30.0000        S  First   
802         1       1  male  11.00      1      2  120.0000        S  First   
839         1       1  male    NaN      0      0   29.7000        C  First   
857         1       1  male  51.00      0      0   26.5500        S  First   
889         1       1  male  26.00      0      0   30.0000        C  First   

       who  adult_male deck  embark_town alive  alone  
23     man        True    A  Southampton   yes   True  
55     man        True    C  Southampton   yes   True  
97     man        True    D    Cherbourg   yes  False  
187    man        True  NaN  Southampton   yes   True  
209    man        True    A    Cherbourg   yes   True  
224    man        True    C  Southampton   yes  False  
248    man        True  

### Array are mutable

In [51]:
arr

array([[85, 40, 13, 42],
       [71, 95, 45, 78],
       [25, 75, 24, 63]])

In [53]:
arr[0,0] = 10

In [54]:
arr

array([[10, 40, 13, 42],
       [71, 95, 45, 78],
       [25, 75, 24, 63]])

### Array concatenation

- Vertical concatenation
- Horizntal concatenation

###    Syntax:
        
            np.concatenate((x,y), axis = 0,1)

In [56]:
x = np.arange(1,10).reshape(3,3)

In [57]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
x.shape

(3, 3)

In [59]:
y = np.array([1,2,3]).reshape(1,3)

In [60]:
y

array([[1, 2, 3]])

In [61]:
np.concatenate((x,y), axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [63]:
y = np.array([1,2,3]).reshape(3,1)

In [64]:
y

array([[1],
       [2],
       [3]])

In [65]:
np.concatenate((x,y), axis = 1)

array([[1, 2, 3, 1],
       [4, 5, 6, 2],
       [7, 8, 9, 3]])

### Array Sorting

    Syntax:
        
        np.sort(arr)
        arr.sort()

### Ascending order

In [67]:
arr = np.random.randint(10,100,15)

In [68]:
arr

array([67, 82, 97, 56, 18, 63, 22, 44, 34, 22, 27, 78, 40, 66, 24])

In [69]:
np.sort(arr)

array([18, 22, 22, 24, 27, 34, 40, 44, 56, 63, 66, 67, 78, 82, 97])

### Descending order

In [70]:
np.sort(arr)[::-1]

array([97, 82, 78, 67, 66, 63, 56, 44, 40, 34, 27, 24, 22, 22, 18])

In [71]:
arr

array([67, 82, 97, 56, 18, 63, 22, 44, 34, 22, 27, 78, 40, 66, 24])

In [84]:
arr = np.random.randint(10,100,15).reshape(3,5)

In [85]:
arr

array([[73, 52, 64, 26, 34],
       [73, 32, 37, 42, 26],
       [85, 68, 70, 64, 80]])

In [87]:
arr.sort(axis = 1)

In [88]:
arr

array([[26, 34, 52, 64, 73],
       [26, 32, 37, 42, 73],
       [64, 68, 70, 80, 85]])

### Arithmetic Operation on Array

In [89]:
arr

array([[26, 34, 52, 64, 73],
       [26, 32, 37, 42, 73],
       [64, 68, 70, 80, 85]])

In [90]:
arr+5

array([[31, 39, 57, 69, 78],
       [31, 37, 42, 47, 78],
       [69, 73, 75, 85, 90]])

In [91]:
arr-5

array([[21, 29, 47, 59, 68],
       [21, 27, 32, 37, 68],
       [59, 63, 65, 75, 80]])

In [92]:
arr*5

array([[130, 170, 260, 320, 365],
       [130, 160, 185, 210, 365],
       [320, 340, 350, 400, 425]])

In [93]:
arr/5

array([[ 5.2,  6.8, 10.4, 12.8, 14.6],
       [ 5.2,  6.4,  7.4,  8.4, 14.6],
       [12.8, 13.6, 14. , 16. , 17. ]])

In [94]:
arr//2

array([[13, 17, 26, 32, 36],
       [13, 16, 18, 21, 36],
       [32, 34, 35, 40, 42]], dtype=int32)

In [95]:
arr%2

array([[0, 0, 0, 0, 1],
       [0, 0, 1, 0, 1],
       [0, 0, 0, 0, 1]], dtype=int32)

In [96]:
arr**3

array([[ 17576,  39304, 140608, 262144, 389017],
       [ 17576,  32768,  50653,  74088, 389017],
       [262144, 314432, 343000, 512000, 614125]], dtype=int32)

### Array Broadcasting

- When we perform some array to array operation on an array of different size then to make the operation possible Numpy adds some dumpy rows and dummy columns to match the shape of both the arrays
- This process is called as Array Broadcasting

__Note__:- Atleast one dimension should be same and the other dimension should be 1 in either of the array

In [97]:
arr

array([[26, 34, 52, 64, 73],
       [26, 32, 37, 42, 73],
       [64, 68, 70, 80, 85]])

In [98]:
arr.shape

(3, 5)

In [101]:
a = np.array([5,5,5,5,5])

In [102]:
a.shape

(5,)

In [ ]:
        [[26, 34, 52, 64, 73],      [[5,5,5,5,5]
         [26, 32, 37, 42, 73],       [5,5,5,5,5]
         [64, 68, 70, 80, 85]]       [5,5,5,5,5]]

In [103]:
arr+5

array([[31, 39, 57, 69, 78],
       [31, 37, 42, 47, 78],
       [69, 73, 75, 85, 90]])

In [104]:
arr

array([[26, 34, 52, 64, 73],
       [26, 32, 37, 42, 73],
       [64, 68, 70, 80, 85]])

In [105]:
arr+7

array([[33, 41, 59, 71, 80],
       [33, 39, 44, 49, 80],
       [71, 75, 77, 87, 92]])

In [106]:
arr

array([[26, 34, 52, 64, 73],
       [26, 32, 37, 42, 73],
       [64, 68, 70, 80, 85]])

In [109]:
arr2 = np.array([1,2,3, 4,5])

In [110]:
arr+arr2

array([[27, 36, 55, 68, 78],
       [27, 34, 40, 46, 78],
       [65, 70, 73, 84, 90]])

In [111]:
arr

array([[26, 34, 52, 64, 73],
       [26, 32, 37, 42, 73],
       [64, 68, 70, 80, 85]])

In [112]:
arr[0,0] = arr[0,0]+10

In [113]:
arr

array([[36, 34, 52, 64, 73],
       [26, 32, 37, 42, 73],
       [64, 68, 70, 80, 85]])

In [114]:
arr+np.array([5,5,5,5,5])


array([[41, 39, 57, 69, 78],
       [31, 37, 42, 47, 78],
       [69, 73, 75, 85, 90]])

In [115]:
arr

array([[36, 34, 52, 64, 73],
       [26, 32, 37, 42, 73],
       [64, 68, 70, 80, 85]])

### Iterate over array

In [116]:
y = np.arange(21)

In [117]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [118]:
for i in y:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [119]:
arr

array([[36, 34, 52, 64, 73],
       [26, 32, 37, 42, 73],
       [64, 68, 70, 80, 85]])

In [120]:
for i in arr:
    print(i)
    print('------')

[36 34 52 64 73]
------
[26 32 37 42 73]
------
[64 68 70 80 85]
------


### np.nditer()

- It returns an iterable object

In [121]:
arr

array([[36, 34, 52, 64, 73],
       [26, 32, 37, 42, 73],
       [64, 68, 70, 80, 85]])

In [122]:
for i in np.nditer(arr):
    print(i)

36
34
52
64
73
26
32
37
42
73
64
68
70
80
85


### Determinant

    [[a,b,c],
     [d,e,f],
     [g,h,i]]

    det=a(ei−fh)−b(di−fg)+c(dh−eg)

In [123]:
arr = np.arange(1,10).reshape(3,3)

In [124]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
int(np.linalg.det(arr))

0